pipeline {
 agent any
 stages {
   stage("Build") {
     steps {
       dir("starter_code") {
         sh "mvn clean install"
       }
     }
   }
   stage("Test") {
     steps {
       dir("starter_code") {
         sh "mvn test"
       }
     }
   }
 }
  post {
         success {
             echo "Build and Test success!!!"
         }
         failure {
             echo 'Build or Test failed!'
         }
         always {
             // delete workspace after when pipeline completely!
             cleanWs()
         }
     }
}
